--- 
- hosts: webservers
  become: yes
  user: ansible
  connection: ssh

  tasks: 
    
    - name: creating a user eshwar
      user: name='{{item}}' state=present
      with_items:
           - raj
           - john
           - bokada


