--- 
- hosts: webservers
  become: yes

  tasks:
    - name: installing httpd on webservers
      action: yum name=httpd  state=present

      notify: start the httpd service

  handlers:
     
     - name: start the httpd service
       action: service name=httpd state=started
